#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <filesystem>
#include <thread>
#include <chrono>
#include <stdexcept>

namespace fs = std::filesystem;

void genfile(const std::string &inp_pth, const std::string &out_pth)
{
    std::ifstream readfile(inp_pth);
    if (!readfile)
        throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] could not open read file \"" + inp_pth + "\"");

    std::stringstream readstream;
    readstream << readfile.rdbuf();

    std::ofstream writefile(out_pth);
    if (!writefile)
        throw std::runtime_error(
            "[ARGUE WITH CPP COMPILER PANIC] could not open write file \"" +
            out_pth + "\"");

    std::string writestring =
        "#ifndef ARGFILE_COMPILER_AUTOGENERATED_H_3212542356\n"
        "#define ARGFILE_COMPILER_AUTOGENERATED_H_3212542356\n"
        "#include <string>\n"
        "class argfile {\n"
        "public:\n"
        "    std::string text = R\"DELIM61436534__(" +
        readstream.str() +
        ")DELIM61436534__\";\n"
        "};\n"
        "#endif\n";

    writefile << writestring;
}

int main(int argc, char **argv)
{
    if (argc < 3)
        throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] read/build paths are not both provided");

    if (argc > 4)
        throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] too many arguments provided");

    const std::string input_path = argv[1];
    const std::string output_path = argv[2];

    bool watch = false;

    if (argc == 4)
    {
        if (std::string(argv[3]) != "--watch")
            throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] unknown option \"" + std::string(argv[3]) + "\"");

        watch = true;
    }
    genfile(input_path, output_path);
    if (!watch)
        return 0;
    std::cout << "Watching \"" << input_path << "\"...\n";

    fs::file_time_type last_write_time = fs::last_write_time(input_path);
    while (true)
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(750));

        try
        {
            fs::file_time_type current_write_time =
                fs::last_write_time(input_path);

            if (current_write_time != last_write_time)
            {
                last_write_time = current_write_time;

                genfile(input_path, output_path);

                std::cout << "Updated \"" << output_path << "\"\n";
            }
        }
        catch (const fs::filesystem_error &e)
        {
            std::cerr << "[ARGUE WITH CPP COMPILER PANIC] " << e.what() << '\n';
        }
    }
}