#include <iostream>
#include <fstream>
#include <string>
#include <sstream>

int main(int argc, char **argv)
{
    if (argc <= 2)
        throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] read/build paths are not both provided");
    if (argc > 3)
        throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] too many arguments provided");

    std::ifstream readfile(argv[1]);
    if (!readfile)
        throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] could not open read file \"" + std::string(argv[1]) + "\"");

    std::stringstream readstream;
    readstream << readfile.rdbuf();
    std::ofstream writefile(argv[2]);
    if (!writefile)
        throw std::runtime_error("[ARGUE WITH CPP COMPILER PANIC] could not open write file \"" + std::string(argv[2]) + "\"");

    std::string writestring = "#ifndef ARGFILE_COMPILER_AUTOGENERATED_H_3212542356\n"
                              "#define ARGFILE_COMPILER_AUTOGENERATED_H_3212542356\n"
                              "#include <string>\n"
                              "class argfile {\n"
                              "public:\n"
                              "    std::string text = R\"DELIM61436534__(" +
                              readstream.str() + ")DELIM61436534__\";\n"
                                                 "};\n#endif\n";

    writefile << writestring;
    writefile.close();
    readfile.close();
}